[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Souce"
authors = [{name = "Gibbs Herbert Akena", email = "herbertakena@amarinfinancial.com"}]
dynamic = ["version", "description"]
